name: Lint Check & Test
on:
  push:
    paths:
      - "client/**"
      - ".github/workflows/client-lintcheck-and-test.yaml"
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 16
          - 18
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          path: "client"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          check-latest: true
          cache: "npm"
      - name: upgrade npm
        run: npm i -g npm@latest

      - name: Install Dependencies
        run: npm ci

      - name: Lint Check & Test
        run: npm run ci
